<a href="https://colab.research.google.com/github/aaeekaayyyyyy/pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
print(torch.__version__)
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

2.8.0+cu126
True
Tesla T4


## **Tensors**

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensot back as python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[1]

tensor([ 9, 10])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

# Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that thet start with full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [16]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5786, 0.3385, 0.8492, 0.8605],
        [0.5995, 0.0864, 0.9820, 0.5032],
        [0.1955, 0.6430, 0.3315, 0.5649]])

In [17]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224)) # color channels (R,G,B), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

# Zeros and Ones

In [18]:
# Create a tensor of all zeroes
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones.dtype

torch.float32

# Creating a range of tensors and tensors-like

In [22]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
one_to_ten = torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
# Creating tensors like
one_to_ten_like = torch.ones_like(input=one_to_ten)
one_to_ten_like

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor datatype

**Note:** Tensor datatype is one of the 3 big issues we face with PyTorch and deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

The right datatype is really important to not get errors and also for the precision in computing

In [25]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # specifies the datatype of the tensor like float32 float16
                               device=None, # what device is your tensor on
                               requires_grad=False # whether or not track gradients with this tensors operations
                               )
float_32_tensor

tensor([3., 6., 9.])

In [26]:
float_32_tensor.dtype

torch.float32

In [27]:
float_16_tensor = float_32_tensor.type(torch.float16) # with this we can tackle the first kind of issue that we face for different datatype
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [28]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [29]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [30]:
float_16_tensor * int_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [31]:
long_tensor = torch.tensor([3,6,9], dtype=torch.long)
long_tensor

tensor([3, 6, 9])

In [32]:
float_16_tensor * long_tensor # Lmao actually this is more robust than I thought but keep the datatypes in mind

tensor([ 9., 36., 81.], dtype=torch.float16)

### Getting information from tensors

1. Tensors not right datatype - to get a datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [33]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.3966, 0.6141, 0.2050, 0.3139],
        [0.1918, 0.9362, 0.4152, 0.0303],
        [0.6997, 0.0663, 0.3840, 0.8995]])

In [34]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.3966, 0.6141, 0.2050, 0.3139],
        [0.1918, 0.9362, 0.4152, 0.0303],
        [0.6997, 0.0663, 0.3840, 0.8995]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors ( tensor operations )

Tensor operations include
* Addition
* Subtraction
* Multiplication ( element-wise)
* Division
* Matrix Multiplication

In [35]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [36]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [37]:
tensor

tensor([1, 2, 3])

In [38]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [39]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [40]:
torch.sub(tensor,10)

tensor([-9, -8, -7])

In [41]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [42]:
torch.div(tensor,2)

tensor([0.5000, 1.0000, 1.5000])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication ( dot product )

In [43]:
# Elemental wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [44]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

### Finding the min, max, mean, sum, etc (tensor aggregation)

In [47]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [49]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [50]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [51]:
# Find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [52]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding positional min and max

In [54]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [56]:
x.argmin()

tensor(0)

In [59]:
torch.argmin(x)

tensor(0)

In [58]:
x.argmax()

tensor(9)

In [60]:
torch.argmax(x)

tensor(9)